// embedded_system.v

// Generated using ACDS version 13.1 162 at 2026.05.12.12:47:38

`timescale 1 ps / 1 ps
module embedded_system (
		input  wire        clk_clk,          //        clk.clk
		input  wire        reset_reset_n,    //      reset.reset_n
		input  wire [7:0]  switches_export,  //   switches.export
		output wire [7:0]  leds_export,      //       leds.export
		output wire [12:0] sdram_wire_addr,  // sdram_wire.addr
		output wire [1:0]  sdram_wire_ba,    //           .ba
		output wire        sdram_wire_cas_n, //           .cas_n
		output wire        sdram_wire_cke,   //           .cke
		output wire        sdram_wire_cs_n,  //           .cs_n
		inout  wire [15:0] sdram_wire_dq,    //           .dq
		output wire [1:0]  sdram_wire_dqm,   //           .dqm
		output wire        sdram_wire_ras_n, //           .ras_n
		output wire        sdram_wire_we_n,  //           .we_n
		output wire [15:0] to_hex_export     //     to_hex.export
	);

	wire  [31:0] mm_interconnect_0_output_s1_writedata;                                // mm_interconnect_0:OUTPUT_s1_writedata -> OUTPUT:writedata
	wire   [1:0] mm_interconnect_0_output_s1_address;                                  // mm_interconnect_0:OUTPUT_s1_address -> OUTPUT:address
	wire         mm_interconnect_0_output_s1_chipselect;                               // mm_interconnect_0:OUTPUT_s1_chipselect -> OUTPUT:chipselect
	wire         mm_interconnect_0_output_s1_write;                                    // mm_interconnect_0:OUTPUT_s1_write -> OUTPUT:write_n
	wire  [31:0] mm_interconnect_0_output_s1_readdata;                                 // OUTPUT:readdata -> mm_interconnect_0:OUTPUT_s1_readdata
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest;            // JTAG_UART:av_waitrequest -> mm_interconnect_0:JTAG_UART_avalon_jtag_slave_waitrequest
	wire  [31:0] mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata;              // mm_interconnect_0:JTAG_UART_avalon_jtag_slave_writedata -> JTAG_UART:av_writedata
	wire   [0:0] mm_interconnect_0_jtag_uart_avalon_jtag_slave_address;                // mm_interconnect_0:JTAG_UART_avalon_jtag_slave_address -> JTAG_UART:av_address
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect;             // mm_interconnect_0:JTAG_UART_avalon_jtag_slave_chipselect -> JTAG_UART:av_chipselect
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_write;                  // mm_interconnect_0:JTAG_UART_avalon_jtag_slave_write -> JTAG_UART:av_write_n
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_read;                   // mm_interconnect_0:JTAG_UART_avalon_jtag_slave_read -> JTAG_UART:av_read_n
	wire  [31:0] mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata;               // JTAG_UART:av_readdata -> mm_interconnect_0:JTAG_UART_avalon_jtag_slave_readdata
	wire  [31:0] mm_interconnect_0_onchip_memory2_0_s1_writedata;                      // mm_interconnect_0:Onchip_memory2_0_s1_writedata -> Onchip_memory2_0:writedata
	wire   [9:0] mm_interconnect_0_onchip_memory2_0_s1_address;                        // mm_interconnect_0:Onchip_memory2_0_s1_address -> Onchip_memory2_0:address
	wire         mm_interconnect_0_onchip_memory2_0_s1_chipselect;                     // mm_interconnect_0:Onchip_memory2_0_s1_chipselect -> Onchip_memory2_0:chipselect
	wire         mm_interconnect_0_onchip_memory2_0_s1_clken;                          // mm_interconnect_0:Onchip_memory2_0_s1_clken -> Onchip_memory2_0:clken
	wire         mm_interconnect_0_onchip_memory2_0_s1_write;                          // mm_interconnect_0:Onchip_memory2_0_s1_write -> Onchip_memory2_0:write
	wire  [31:0] mm_interconnect_0_onchip_memory2_0_s1_readdata;                       // Onchip_memory2_0:readdata -> mm_interconnect_0:Onchip_memory2_0_s1_readdata
	wire   [3:0] mm_interconnect_0_onchip_memory2_0_s1_byteenable;                     // mm_interconnect_0:Onchip_memory2_0_s1_byteenable -> Onchip_memory2_0:byteenable
	wire         mm_interconnect_0_sdram_s1_waitrequest;                               // SDRAM:za_waitrequest -> mm_interconnect_0:SDRAM_s1_waitrequest
	wire  [15:0] mm_interconnect_0_sdram_s1_writedata;                                 // mm_interconnect_0:SDRAM_s1_writedata -> SDRAM:az_data
	wire  [23:0] mm_interconnect_0_sdram_s1_address;                                   // mm_interconnect_0:SDRAM_s1_address -> SDRAM:az_addr
	wire         mm_interconnect_0_sdram_s1_chipselect;                                // mm_interconnect_0:SDRAM_s1_chipselect -> SDRAM:az_cs
	wire         mm_interconnect_0_sdram_s1_write;                                     // mm_interconnect_0:SDRAM_s1_write -> SDRAM:az_wr_n
	wire         mm_interconnect_0_sdram_s1_read;                                      // mm_interconnect_0:SDRAM_s1_read -> SDRAM:az_rd_n
	wire  [15:0] mm_interconnect_0_sdram_s1_readdata;                                  // SDRAM:za_data -> mm_interconnect_0:SDRAM_s1_readdata
	wire         mm_interconnect_0_sdram_s1_readdatavalid;                             // SDRAM:za_valid -> mm_interconnect_0:SDRAM_s1_readdatavalid
	wire   [1:0] mm_interconnect_0_sdram_s1_byteenable;                                // mm_interconnect_0:SDRAM_s1_byteenable -> SDRAM:az_be_n
	wire         nios2_qsys_0_data_master_waitrequest;                                 // mm_interconnect_0:nios2_qsys_0_data_master_waitrequest -> nios2_qsys_0:d_waitrequest
	wire  [31:0] nios2_qsys_0_data_master_writedata;                                   // nios2_qsys_0:d_writedata -> mm_interconnect_0:nios2_qsys_0_data_master_writedata
	wire  [26:0] nios2_qsys_0_data_master_address;                                     // nios2_qsys_0:d_address -> mm_interconnect_0:nios2_qsys_0_data_master_address
	wire         nios2_qsys_0_data_master_write;                                       // nios2_qsys_0:d_write -> mm_interconnect_0:nios2_qsys_0_data_master_write
	wire         nios2_qsys_0_data_master_read;                                        // nios2_qsys_0:d_read -> mm_interconnect_0:nios2_qsys_0_data_master_read
	wire  [31:0] nios2_qsys_0_data_master_readdata;                                    // mm_interconnect_0:nios2_qsys_0_data_master_readdata -> nios2_qsys_0:d_readdata
	wire         nios2_qsys_0_data_master_debugaccess;                                 // nios2_qsys_0:jtag_debug_module_debugaccess_to_roms -> mm_interconnect_0:nios2_qsys_0_data_master_debugaccess
	wire   [3:0] nios2_qsys_0_data_master_byteenable;                                  // nios2_qsys_0:d_byteenable -> mm_interconnect_0:nios2_qsys_0_data_master_byteenable
	wire  [15:0] mm_interconnect_0_reg16_avalon_interface_0_avalon_slave_0_writedata;  // mm_interconnect_0:reg16_avalon_interface_0_avalon_slave_0_writedata -> reg16_avalon_interface_0:writedata
	wire         mm_interconnect_0_reg16_avalon_interface_0_avalon_slave_0_chipselect; // mm_interconnect_0:reg16_avalon_interface_0_avalon_slave_0_chipselect -> reg16_avalon_interface_0:chipselect
	wire         mm_interconnect_0_reg16_avalon_interface_0_avalon_slave_0_write;      // mm_interconnect_0:reg16_avalon_interface_0_avalon_slave_0_write -> reg16_avalon_interface_0:write
	wire         mm_interconnect_0_reg16_avalon_interface_0_avalon_slave_0_read;       // mm_interconnect_0:reg16_avalon_interface_0_avalon_slave_0_read -> reg16_avalon_interface_0:read
	wire  [15:0] mm_interconnect_0_reg16_avalon_interface_0_avalon_slave_0_readdata;   // reg16_avalon_interface_0:readdata -> mm_interconnect_0:reg16_avalon_interface_0_avalon_slave_0_readdata
	wire   [1:0] mm_interconnect_0_reg16_avalon_interface_0_avalon_slave_0_byteenable; // mm_interconnect_0:reg16_avalon_interface_0_avalon_slave_0_byteenable -> reg16_avalon_interface_0:byteenable
	wire   [1:0] mm_interconnect_0_input_s1_address;                                   // mm_interconnect_0:INPUT_s1_address -> INPUT:address
	wire  [31:0] mm_interconnect_0_input_s1_readdata;                                  // INPUT:readdata -> mm_interconnect_0:INPUT_s1_readdata
	wire         mm_interconnect_0_nios2_qsys_0_jtag_debug_module_waitrequest;         // nios2_qsys_0:jtag_debug_module_waitrequest -> mm_interconnect_0:nios2_qsys_0_jtag_debug_module_waitrequest
	wire  [31:0] mm_interconnect_0_nios2_qsys_0_jtag_debug_module_writedata;           // mm_interconnect_0:nios2_qsys_0_jtag_debug_module_writedata -> nios2_qsys_0:jtag_debug_module_writedata
	wire   [8:0] mm_interconnect_0_nios2_qsys_0_jtag_debug_module_address;             // mm_interconnect_0:nios2_qsys_0_jtag_debug_module_address -> nios2_qsys_0:jtag_debug_module_address
	wire         mm_interconnect_0_nios2_qsys_0_jtag_debug_module_write;               // mm_interconnect_0:nios2_qsys_0_jtag_debug_module_write -> nios2_qsys_0:jtag_debug_module_write
	wire         mm_interconnect_0_nios2_qsys_0_jtag_debug_module_read;                // mm_interconnect_0:nios2_qsys_0_jtag_debug_module_read -> nios2_qsys_0:jtag_debug_module_read
	wire  [31:0] mm_interconnect_0_nios2_qsys_0_jtag_debug_module_readdata;            // nios2_qsys_0:jtag_debug_module_readdata -> mm_interconnect_0:nios2_qsys_0_jtag_debug_module_readdata
	wire         mm_interconnect_0_nios2_qsys_0_jtag_debug_module_debugaccess;         // mm_interconnect_0:nios2_qsys_0_jtag_debug_module_debugaccess -> nios2_qsys_0:jtag_debug_module_debugaccess
	wire   [3:0] mm_interconnect_0_nios2_qsys_0_jtag_debug_module_byteenable;          // mm_interconnect_0:nios2_qsys_0_jtag_debug_module_byteenable -> nios2_qsys_0:jtag_debug_module_byteenable
	wire         nios2_qsys_0_instruction_master_waitrequest;                          // mm_interconnect_0:nios2_qsys_0_instruction_master_waitrequest -> nios2_qsys_0:i_waitrequest
	wire  [26:0] nios2_qsys_0_instruction_master_address;                              // nios2_qsys_0:i_address -> mm_interconnect_0:nios2_qsys_0_instruction_master_address
	wire         nios2_qsys_0_instruction_master_read;                                 // nios2_qsys_0:i_read -> mm_interconnect_0:nios2_qsys_0_instruction_master_read
	wire  [31:0] nios2_qsys_0_instruction_master_readdata;                             // mm_interconnect_0:nios2_qsys_0_instruction_master_readdata -> nios2_qsys_0:i_readdata
	wire         irq_mapper_receiver0_irq;                                             // JTAG_UART:av_irq -> irq_mapper:receiver0_irq
	wire  [31:0] nios2_qsys_0_d_irq_irq;                                               // irq_mapper:sender_irq -> nios2_qsys_0:d_irq
	wire         rst_controller_reset_out_reset;                                       // rst_controller:reset_out -> [INPUT:reset_n, JTAG_UART:rst_n, OUTPUT:reset_n, Onchip_memory2_0:reset, SDRAM:reset_n, irq_mapper:reset, mm_interconnect_0:nios2_qsys_0_reset_n_reset_bridge_in_reset_reset, nios2_qsys_0:reset_n, rst_translator:in_reset]
	wire         rst_controller_reset_out_reset_req;                                   // rst_controller:reset_req -> [Onchip_memory2_0:reset_req, nios2_qsys_0:reset_req, rst_translator:reset_req_in]
	wire         nios2_qsys_0_jtag_debug_module_reset_reset;                           // nios2_qsys_0:jtag_debug_module_resetrequest -> rst_controller:reset_in1
	wire         rst_controller_001_reset_out_reset;                                   // rst_controller_001:reset_out -> [mm_interconnect_0:reg16_avalon_interface_0_reset_sink_reset_bridge_in_reset_reset, reg16_avalon_interface_0:resetn]

	embedded_system_nios2_qsys_0 nios2_qsys_0 (
		.clk                                   (clk_clk),                                                      //                       clk.clk
		.reset_n                               (~rst_controller_reset_out_reset),                              //                   reset_n.reset_n
		.reset_req                             (rst_controller_reset_out_reset_req),                           //                          .reset_req
		.d_address                             (nios2_qsys_0_data_master_address),                             //               data_master.address
		.d_byteenable                          (nios2_qsys_0_data_master_byteenable),                          //                          .byteenable
		.d_read                                (nios2_qsys_0_data_master_read),                                //                          .read
		.d_readdata                            (nios2_qsys_0_data_master_readdata),                            //                          .readdata
		.d_waitrequest                         (nios2_qsys_0_data_master_waitrequest),                         //                          .waitrequest
		.d_write                               (nios2_qsys_0_data_master_write),                               //                          .write
		.d_writedata                           (nios2_qsys_0_data_master_writedata),                           //                          .writedata
		.jtag_debug_module_debugaccess_to_roms (nios2_qsys_0_data_master_debugaccess),                         //                          .debugaccess
		.i_address                             (nios2_qsys_0_instruction_master_address),                      //        instruction_master.address
		.i_read                                (nios2_qsys_0_instruction_master_read),                         //                          .read
		.i_readdata                            (nios2_qsys_0_instruction_master_readdata),                     //                          .readdata
		.i_waitrequest                         (nios2_qsys_0_instruction_master_waitrequest),                  //                          .waitrequest
		.d_irq                                 (nios2_qsys_0_d_irq_irq),                                       //                     d_irq.irq
		.jtag_debug_module_resetrequest        (nios2_qsys_0_jtag_debug_module_reset_reset),                   //   jtag_debug_module_reset.reset
		.jtag_debug_module_address             (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_address),     //         jtag_debug_module.address
		.jtag_debug_module_byteenable          (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_byteenable),  //                          .byteenable
		.jtag_debug_module_debugaccess         (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_debugaccess), //                          .debugaccess
		.jtag_debug_module_read                (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_read),        //                          .read
		.jtag_debug_module_readdata            (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_readdata),    //                          .readdata
		.jtag_debug_module_waitrequest         (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_waitrequest), //                          .waitrequest
		.jtag_debug_module_write               (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_write),       //                          .write
		.jtag_debug_module_writedata           (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_writedata),   //                          .writedata
		.no_ci_readra                          ()                                                              // custom_instruction_master.readra
	);

	embedded_system_Onchip_memory2_0 onchip_memory2_0 (
		.clk        (clk_clk),                                          //   clk1.clk
		.address    (mm_interconnect_0_onchip_memory2_0_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_onchip_memory2_0_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_onchip_memory2_0_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_onchip_memory2_0_s1_write),      //       .write
		.readdata   (mm_interconnect_0_onchip_memory2_0_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_onchip_memory2_0_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_onchip_memory2_0_s1_byteenable), //       .byteenable
		.reset      (rst_controller_reset_out_reset),                   // reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req)                //       .reset_req
	);

	embedded_system_INPUT input_inst (
		.clk      (clk_clk),                             //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),     //               reset.reset_n
		.address  (mm_interconnect_0_input_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_input_s1_readdata), //                    .readdata
		.in_port  (switches_export)                      // external_connection.export
	);

	embedded_system_OUTPUT output_inst (
		.clk        (clk_clk),                                //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),        //               reset.reset_n
		.address    (mm_interconnect_0_output_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_output_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_output_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_output_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_output_s1_readdata),   //                    .readdata
		.out_port   (leds_export)                             // external_connection.export
	);

	embedded_system_JTAG_UART jtag_uart (
		.clk            (clk_clk),                                                   //               clk.clk
		.rst_n          (~rst_controller_reset_out_reset),                           //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_jtag_uart_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_jtag_uart_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_jtag_uart_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver0_irq)                                   //               irq.irq
	);

	embedded_system_SDRAM sdram (
		.clk            (clk_clk),                                  //   clk.clk
		.reset_n        (~rst_controller_reset_out_reset),          // reset.reset_n
		.az_addr        (mm_interconnect_0_sdram_s1_address),       //    s1.address
		.az_be_n        (~mm_interconnect_0_sdram_s1_byteenable),   //      .byteenable_n
		.az_cs          (mm_interconnect_0_sdram_s1_chipselect),    //      .chipselect
		.az_data        (mm_interconnect_0_sdram_s1_writedata),     //      .writedata
		.az_rd_n        (~mm_interconnect_0_sdram_s1_read),         //      .read_n
		.az_wr_n        (~mm_interconnect_0_sdram_s1_write),        //      .write_n
		.za_data        (mm_interconnect_0_sdram_s1_readdata),      //      .readdata
		.za_valid       (mm_interconnect_0_sdram_s1_readdatavalid), //      .readdatavalid
		.za_waitrequest (mm_interconnect_0_sdram_s1_waitrequest),   //      .waitrequest
		.zs_addr        (sdram_wire_addr),                          //  wire.export
		.zs_ba          (sdram_wire_ba),                            //      .export
		.zs_cas_n       (sdram_wire_cas_n),                         //      .export
		.zs_cke         (sdram_wire_cke),                           //      .export
		.zs_cs_n        (sdram_wire_cs_n),                          //      .export
		.zs_dq          (sdram_wire_dq),                            //      .export
		.zs_dqm         (sdram_wire_dqm),                           //      .export
		.zs_ras_n       (sdram_wire_ras_n),                         //      .export
		.zs_we_n        (sdram_wire_we_n)                           //      .export
	);

	reg16_avalon_interface reg16_avalon_interface_0 (
		.writedata  (mm_interconnect_0_reg16_avalon_interface_0_avalon_slave_0_writedata),  // avalon_slave_0.writedata
		.readdata   (mm_interconnect_0_reg16_avalon_interface_0_avalon_slave_0_readdata),   //               .readdata
		.write      (mm_interconnect_0_reg16_avalon_interface_0_avalon_slave_0_write),      //               .write
		.read       (mm_interconnect_0_reg16_avalon_interface_0_avalon_slave_0_read),       //               .read
		.byteenable (mm_interconnect_0_reg16_avalon_interface_0_avalon_slave_0_byteenable), //               .byteenable
		.chipselect (mm_interconnect_0_reg16_avalon_interface_0_avalon_slave_0_chipselect), //               .chipselect
		.resetn     (~rst_controller_001_reset_out_reset),                                  //     reset_sink.reset_n
		.Q_export   (to_hex_export),                                                        //    conduit_end.export
		.clock      (clk_clk)                                                               //     clock_sink.clk
	);

	embedded_system_mm_interconnect_0 mm_interconnect_0 (
		.clk_0_clk_clk                                                   (clk_clk),                                                              //                                                 clk_0_clk.clk
		.nios2_qsys_0_reset_n_reset_bridge_in_reset_reset                (rst_controller_reset_out_reset),                                       //                nios2_qsys_0_reset_n_reset_bridge_in_reset.reset
		.reg16_avalon_interface_0_reset_sink_reset_bridge_in_reset_reset (rst_controller_001_reset_out_reset),                                   // reg16_avalon_interface_0_reset_sink_reset_bridge_in_reset.reset
		.nios2_qsys_0_data_master_address                                (nios2_qsys_0_data_master_address),                                     //                                  nios2_qsys_0_data_master.address
		.nios2_qsys_0_data_master_waitrequest                            (nios2_qsys_0_data_master_waitrequest),                                 //                                                          .waitrequest
		.nios2_qsys_0_data_master_byteenable                             (nios2_qsys_0_data_master_byteenable),                                  //                                                          .byteenable
		.nios2_qsys_0_data_master_read                                   (nios2_qsys_0_data_master_read),                                        //                                                          .read
		.nios2_qsys_0_data_master_readdata                               (nios2_qsys_0_data_master_readdata),                                    //                                                          .readdata
		.nios2_qsys_0_data_master_write                                  (nios2_qsys_0_data_master_write),                                       //                                                          .write
		.nios2_qsys_0_data_master_writedata                              (nios2_qsys_0_data_master_writedata),                                   //                                                          .writedata
		.nios2_qsys_0_data_master_debugaccess                            (nios2_qsys_0_data_master_debugaccess),                                 //                                                          .debugaccess
		.nios2_qsys_0_instruction_master_address                         (nios2_qsys_0_instruction_master_address),                              //                           nios2_qsys_0_instruction_master.address
		.nios2_qsys_0_instruction_master_waitrequest                     (nios2_qsys_0_instruction_master_waitrequest),                          //                                                          .waitrequest
		.nios2_qsys_0_instruction_master_read                            (nios2_qsys_0_instruction_master_read),                                 //                                                          .read
		.nios2_qsys_0_instruction_master_readdata                        (nios2_qsys_0_instruction_master_readdata),                             //                                                          .readdata
		.INPUT_s1_address                                                (mm_interconnect_0_input_s1_address),                                   //                                                  INPUT_s1.address
		.INPUT_s1_readdata                                               (mm_interconnect_0_input_s1_readdata),                                  //                                                          .readdata
		.JTAG_UART_avalon_jtag_slave_address                             (mm_interconnect_0_jtag_uart_avalon_jtag_slave_address),                //                               JTAG_UART_avalon_jtag_slave.address
		.JTAG_UART_avalon_jtag_slave_write                               (mm_interconnect_0_jtag_uart_avalon_jtag_slave_write),                  //                                                          .write
		.JTAG_UART_avalon_jtag_slave_read                                (mm_interconnect_0_jtag_uart_avalon_jtag_slave_read),                   //                                                          .read
		.JTAG_UART_avalon_jtag_slave_readdata                            (mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata),               //                                                          .readdata
		.JTAG_UART_avalon_jtag_slave_writedata                           (mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata),              //                                                          .writedata
		.JTAG_UART_avalon_jtag_slave_waitrequest                         (mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest),            //                                                          .waitrequest
		.JTAG_UART_avalon_jtag_slave_chipselect                          (mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect),             //                                                          .chipselect
		.nios2_qsys_0_jtag_debug_module_address                          (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_address),             //                            nios2_qsys_0_jtag_debug_module.address
		.nios2_qsys_0_jtag_debug_module_write                            (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_write),               //                                                          .write
		.nios2_qsys_0_jtag_debug_module_read                             (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_read),                //                                                          .read
		.nios2_qsys_0_jtag_debug_module_readdata                         (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_readdata),            //                                                          .readdata
		.nios2_qsys_0_jtag_debug_module_writedata                        (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_writedata),           //                                                          .writedata
		.nios2_qsys_0_jtag_debug_module_byteenable                       (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_byteenable),          //                                                          .byteenable
		.nios2_qsys_0_jtag_debug_module_waitrequest                      (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_waitrequest),         //                                                          .waitrequest
		.nios2_qsys_0_jtag_debug_module_debugaccess                      (mm_interconnect_0_nios2_qsys_0_jtag_debug_module_debugaccess),         //                                                          .debugaccess
		.Onchip_memory2_0_s1_address                                     (mm_interconnect_0_onchip_memory2_0_s1_address),                        //                                       Onchip_memory2_0_s1.address
		.Onchip_memory2_0_s1_write                                       (mm_interconnect_0_onchip_memory2_0_s1_write),                          //                                                          .write
		.Onchip_memory2_0_s1_readdata                                    (mm_interconnect_0_onchip_memory2_0_s1_readdata),                       //                                                          .readdata
		.Onchip_memory2_0_s1_writedata                                   (mm_interconnect_0_onchip_memory2_0_s1_writedata),                      //                                                          .writedata
		.Onchip_memory2_0_s1_byteenable                                  (mm_interconnect_0_onchip_memory2_0_s1_byteenable),                     //                                                          .byteenable
		.Onchip_memory2_0_s1_chipselect                                  (mm_interconnect_0_onchip_memory2_0_s1_chipselect),                     //                                                          .chipselect
		.Onchip_memory2_0_s1_clken                                       (mm_interconnect_0_onchip_memory2_0_s1_clken),                          //                                                          .clken
		.OUTPUT_s1_address                                               (mm_interconnect_0_output_s1_address),                                  //                                                 OUTPUT_s1.address
		.OUTPUT_s1_write                                                 (mm_interconnect_0_output_s1_write),                                    //                                                          .write
		.OUTPUT_s1_readdata                                              (mm_interconnect_0_output_s1_readdata),                                 //                                                          .readdata
		.OUTPUT_s1_writedata                                             (mm_interconnect_0_output_s1_writedata),                                //                                                          .writedata
		.OUTPUT_s1_chipselect                                            (mm_interconnect_0_output_s1_chipselect),                               //                                                          .chipselect
		.reg16_avalon_interface_0_avalon_slave_0_write                   (mm_interconnect_0_reg16_avalon_interface_0_avalon_slave_0_write),      //                   reg16_avalon_interface_0_avalon_slave_0.write
		.reg16_avalon_interface_0_avalon_slave_0_read                    (mm_interconnect_0_reg16_avalon_interface_0_avalon_slave_0_read),       //                                                          .read
		.reg16_avalon_interface_0_avalon_slave_0_readdata                (mm_interconnect_0_reg16_avalon_interface_0_avalon_slave_0_readdata),   //                                                          .readdata
		.reg16_avalon_interface_0_avalon_slave_0_writedata               (mm_interconnect_0_reg16_avalon_interface_0_avalon_slave_0_writedata),  //                                                          .writedata
		.reg16_avalon_interface_0_avalon_slave_0_byteenable              (mm_interconnect_0_reg16_avalon_interface_0_avalon_slave_0_byteenable), //                                                          .byteenable
		.reg16_avalon_interface_0_avalon_slave_0_chipselect              (mm_interconnect_0_reg16_avalon_interface_0_avalon_slave_0_chipselect), //                                                          .chipselect
		.SDRAM_s1_address                                                (mm_interconnect_0_sdram_s1_address),                                   //                                                  SDRAM_s1.address
		.SDRAM_s1_write                                                  (mm_interconnect_0_sdram_s1_write),                                     //                                                          .write
		.SDRAM_s1_read                                                   (mm_interconnect_0_sdram_s1_read),                                      //                                                          .read
		.SDRAM_s1_readdata                                               (mm_interconnect_0_sdram_s1_readdata),                                  //                                                          .readdata
		.SDRAM_s1_writedata                                              (mm_interconnect_0_sdram_s1_writedata),                                 //                                                          .writedata
		.SDRAM_s1_byteenable                                             (mm_interconnect_0_sdram_s1_byteenable),                                //                                                          .byteenable
		.SDRAM_s1_readdatavalid                                          (mm_interconnect_0_sdram_s1_readdatavalid),                             //                                                          .readdatavalid
		.SDRAM_s1_waitrequest                                            (mm_interconnect_0_sdram_s1_waitrequest),                               //                                                          .waitrequest
		.SDRAM_s1_chipselect                                             (mm_interconnect_0_sdram_s1_chipselect)                                 //                                                          .chipselect
	);

	embedded_system_irq_mapper irq_mapper (
		.clk           (clk_clk),                        //       clk.clk
		.reset         (rst_controller_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),       // receiver0.irq
		.sender_irq    (nios2_qsys_0_d_irq_irq)          //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (2),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                             // reset_in0.reset
		.reset_in1      (nios2_qsys_0_jtag_debug_module_reset_reset), // reset_in1.reset
		.clk            (clk_clk),                                    //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),             // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req),         //          .reset_req
		.reset_req_in0  (1'b0),                                       // (terminated)
		.reset_req_in1  (1'b0),                                       // (terminated)
		.reset_in2      (1'b0),                                       // (terminated)
		.reset_req_in2  (1'b0),                                       // (terminated)
		.reset_in3      (1'b0),                                       // (terminated)
		.reset_req_in3  (1'b0),                                       // (terminated)
		.reset_in4      (1'b0),                                       // (terminated)
		.reset_req_in4  (1'b0),                                       // (terminated)
		.reset_in5      (1'b0),                                       // (terminated)
		.reset_req_in5  (1'b0),                                       // (terminated)
		.reset_in6      (1'b0),                                       // (terminated)
		.reset_req_in6  (1'b0),                                       // (terminated)
		.reset_in7      (1'b0),                                       // (terminated)
		.reset_req_in7  (1'b0),                                       // (terminated)
		.reset_in8      (1'b0),                                       // (terminated)
		.reset_req_in8  (1'b0),                                       // (terminated)
		.reset_in9      (1'b0),                                       // (terminated)
		.reset_req_in9  (1'b0),                                       // (terminated)
		.reset_in10     (1'b0),                                       // (terminated)
		.reset_req_in10 (1'b0),                                       // (terminated)
		.reset_in11     (1'b0),                                       // (terminated)
		.reset_req_in11 (1'b0),                                       // (terminated)
		.reset_in12     (1'b0),                                       // (terminated)
		.reset_req_in12 (1'b0),                                       // (terminated)
		.reset_in13     (1'b0),                                       // (terminated)
		.reset_req_in13 (1'b0),                                       // (terminated)
		.reset_in14     (1'b0),                                       // (terminated)
		.reset_req_in14 (1'b0),                                       // (terminated)
		.reset_in15     (1'b0),                                       // (terminated)
		.reset_req_in15 (1'b0)                                        // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset), // reset_out.reset
		.reset_req      (),                                   // (terminated)
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
